image: gcc

before_script:
 - apt-get update --yes
 - apt-get install --yes cmake
 - apt-get install ninja-build
 - apt-get install doxygen --assume-yes
 - apt-get install build-essential
 - apt-get install qt5-default

stages:
  - info
  - build

info-job:
  tags:
    - alpine-docker
  stage: info
  script:
    - pwd
    - ls

build-job:
  tags:
    - alpine-docker
  stage: build
  artifacts:
    paths:
    - BUILD/Documentation/
  script:
    - echo "Building..."
    - mkdir BUILD
    - cd BUILD
    - cmake -G "Ninja" ../Sources
    - ninja
    - echo "Build complete"
    - echo "Testing..."
    - ./tests
    - cmake --build . --target BuildDoc


