image: gcc

before_script:
 - apt-get update --yes
 - apt-get install --yes cmake
 - apt-get install ninja-build
 - apt-get install doxygen --assume-yes

stages:
  - info
  - build
  - test
  - deploy

info-job:
  tags:
    - alpine-docker
  stage: info
  script:
    - pwd
    - ls

build-job:
  tags:
    - alpine-docker
  stage: build
  artifacts:
    paths:
    - BUILD/Documentation/
  script:
    - mkdir BUILD
    - cd BUILD
    - cmake -G "Ninja" ../Sources
    - ninja
    - ./tests
    - cmake --build . --target BuildDoc

test-job:
  tags:
    - alpine-docker
  stage: test
  script:
    - echo "Running tests..."

deploy-job:
  tags:
    - alpine-docker
  stage: deploy
  script:
    - echo "Deploying..."
